### PR TITLE
Feature a new katana

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
~⚠️ Don't merge yet. 😄~

The goal is to up `katana_code` in a way that this plugin can be imported without issue elsewhere.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
https://github.com/project-fifo/rebar3_lint/actions/runs/5428699668/jobs/9873132527?pr=52#step:4:58 happens because we have stuff like e.g. a branch instead of a tag. Message is not super helpful for development, though, should try to make it more explicit.

**Comment by paulo-ferraz-oliveira** [comment]
Once CI is Ok, and this bump is approved/merged, I'd kindly request a release. Thanks.

**Review by elbrujohalcon — APPROVED** [review]

**Comment by elbrujohalcon** [comment]
Done: https://hex.pm/packages/rebar3_lint/3.0.1

**Comment by elbrujohalcon** [comment]
Done: https://hex.pm/packages/rebar3_lint/3.0.1

**Pull request merged**
