### PR TITLE
Fix #28: Update elvis_core for a new release

### LINKED ISSUE #28: Release request
After inaka/elvis_core#188 we should release this one, and publish to Hex.pm.

### PR DESCRIPTION
**Pull request by elbrujohalcon**

### CODE REVIEW

**Review by paulo-ferraz-oliveira — APPROVED** [review]
Look's good. Will merge.

**Comment by paulo-ferraz-oliveira** [comment]
@elbrujohalcon, do you wanna publish it to Hex.pm or shall I?

**Comment by elbrujohalcon** [comment]
Go for it, @paulo-ferraz-oliveira

**Comment by paulo-ferraz-oliveira** [comment]
Done: https://github.com/project-fifo/rebar3_lint/releases/tag/v0.4.0, and
Done: https://hex.pm/packages/rebar3_lint/0.4.0

**Pull request merged**
