### PR TITLE
Add missing comma in `elvis.config` default

### PR DESCRIPTION
**Pull request by Stratus3D**

### CODE REVIEW

**Review by elbrujohalcon — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
The fix is Ok, the default isn't 🤣 

It's actually (as per the code)

```erlang
[#{ dirs => ["apps/*/src/**", "src/**"],
    filter => "*.erl",
    ruleset => erl_files },
 #{ dirs => ["."],
    filter => "rebar.config",
    ruleset => rebar_config }
 #{ dirs => ["."],
    filter => "elvis.config",
    ruleset => elvis_config }]
```

but @elbrujohalcon is busy with https://github.com/spawnfest, so no-time is understandable 😄

**Comment by paulo-ferraz-oliveira** [comment]
And this actually showed a bug in the code. Nice 😄

**Comment by Stratus3D** [comment]
@paulo-ferraz-oliveira what should the config look like if I want to also run the linter on my CT tests in the `test/` directory?

**Comment by paulo-ferraz-oliveira** [comment]
Just add `test/**` to the appropriate block.

Example: https://github.com/miniclip/poolgirl/blob/master/elvis.config#L7

**Pull request merged**
