### PR TITLE
Properly report first exception

### PR DESCRIPTION
**Pull request by filmor**

### CODE REVIEW

**Review by elbrujohalcon — APPROVED** [review]

**Comment by filmor** [comment]
Dialyzer not being happy with it just means that `elvis_core` is incorrectly speced (and not correctly checked by Dialyzer?), I'll have a look. With the current implementation, the case in question (forgot to set the `ruleset` value) will lead to "Linting failed" without any additional information.

**Comment by elbrujohalcon** [comment]
> Dialyzer not being happy with it just means that `elvis_core` is incorrectly speced (and not correctly checked by Dialyzer?), I'll have a look. With the current implementation, the case in question (forgot to set the `ruleset` value) will lead to "Linting failed" without any additional information.

Let's open a ticket in `elvis_core` to adjust the specs, then :)

**Comment by paulo-ferraz-oliveira** [comment]
I don't see where `elvis_core` exceptions are "thrown" as `{fail, [{throw, Error}|_]}`, or what's catching them to transform an error into that, but I agree the tests could help developers by being more explicit in cases of e.g. badmatches.

**Comment by paulo-ferraz-oliveira** [comment]
Once https://github.com/inaka/elvis_core/pull/314 is approved+merged+tagged+released, this pull request can be updated to benefit from that and then approved+...

**Comment by paulo-ferraz-oliveira** [comment]
The above-mentioned pull request is in place, so this pull request can benefit from it.

**Comment by paulo-ferraz-oliveira** [comment]
Closing as superseded by #60. This seemed stale, and the solution seemed incomplete too. That, along with the Conflicting files, eased our choice.

**Pull request closed without merging**
