### PR TITLE
Make output format configurable

### PR DESCRIPTION
**Pull request by cypherfox**
This adds a rebar configuration setting (elvis_output_format) that allows the control of the output format from the rebar.config

Also adds the nessecary documentation in the Readme.md

The changes also switches to the tip of the master when pulling evlis_core

The force of the output_format to plain mentioned in one of the commits has been removed. The code will now use the default of elvis_core

### CODE REVIEW

**Comment by Licenser** [comment]
Hi cypherfox, this is awesome!

The only thing that catches my eye is the master branch for elvis. I can see the reasoning here that the rebar.lock keeps the exact tag but it still feels wrong using master instead. of either a tag or a version.

I'd lean towards a fixed version personally. I know it was a tag before and I don't remember why it wasn't a version wich is partially why I'd preffer sticking to version it makes the reasoning easier when you are as forgetful as me.

**Comment by cypherfox** [comment]
Ah! I had never seen a rebar.lock file distributed with the project before.

I have no strong feelings on the version. I have since found out, that my problems where not from an older version of elvis_core being pulled. But I do dislike explicit revisions in dependency declarations. How about tag 0.3.2`?

**Comment by Licenser** [comment]
`{tag 0.3.2}` sounds good. basically the reason I like to make things stick like that is that breaking changes upstream doesn't affect my code but it's at the expense of having to keep up to date with the upstream changes actively.

**Comment by Licenser** [comment]
did you run rebar3 upgrade after that change? the lock file didn't seem to have changed.

**Comment by cypherfox** [comment]
Sorry, I build external to my source tree and had used rebar.lock never before. Should be up to date now. Is it actually nessecary?

**Comment by Licenser** [comment]
how rebar.lock work is that unless you run rebar3 upgrade the version changes don't take effect for builds.

It goes along the line of re-producible builds. The idea being that everything send to git (or your favourite tool) will build exactly the same no mater at what time you check it out.

Also awesome and thanks!

**Pull request merged**
