### PR TITLE
Support/fix optional else clause for maybe block

### PR DESCRIPTION
**Pull request by belltoy**
- https://github.com/inaka/katana-code/pull/75
- https://github.com/inaka/elvis_core/pull/261

### CODE REVIEW

**Comment by elbrujohalcon** [comment]
@paulo-ferraz-oliveira do you know what's up with Github actions not finding Erlang/OTP 23? 🤔

**Comment by paulo-ferraz-oliveira** [comment]
Most probably because [it's not compatible with Ubuntu 22.04](https://repo.hex.pm/builds/otp/ubuntu-22.04/builds.txt).

**Comment by elbrujohalcon** [comment]
Should we remove that check, then?

**Comment by paulo-ferraz-oliveira** [comment]
(which means we can still support 25, 24 and 23, as OTP and `rebar3` do - though we don't have a support interval intention made explicit anywhere)

**Comment by elbrujohalcon** [comment]
Do you mind including that adjustment in your PR, @belltoy?

**Review by paulo-ferraz-oliveira — APPROVED** [review]
With CI passing, I approve this.

**Comment by elbrujohalcon** [comment]
@paulo-ferraz-oliveira do you mind generating the new release and publishing it to hex.pm?

**Comment by paulo-ferraz-oliveira** [comment]
Ok, sure.

**Comment by paulo-ferraz-oliveira** [comment]
Published, as 2.0.1:

* [on GitHub](https://github.com/project-fifo/rebar3_lint/releases/tag/2.0.1)
* [on Hex.pm](https://hex.pm/packages/rebar3_lint/2.0.1)

Thanks for your contribution, @belltoy.

**Pull request merged**
